<?php

use Illuminate\Database\Seeder;

class PermissionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permissions')->delete();
        
        \DB::table('permissions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'view-backend',
                'display_name' => 'View Backend',
                'sort' => 1,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'view-frontend',
                'display_name' => 'View Frontend',
                'sort' => 2,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'view-access-management',
                'display_name' => 'View Access Management',
                'sort' => 3,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'view-user-management',
                'display_name' => 'View User Management',
                'sort' => 4,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'view-active-user',
                'display_name' => 'View Active User',
                'sort' => 5,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'view-deactive-user',
                'display_name' => 'View Deactive User',
                'sort' => 6,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'view-deleted-user',
                'display_name' => 'View Deleted User',
                'sort' => 7,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'show-user',
                'display_name' => 'Show User Details',
                'sort' => 8,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'create-user',
                'display_name' => 'Create User',
                'sort' => 9,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'edit-user',
                'display_name' => 'Edit User',
                'sort' => 9,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'delete-user',
                'display_name' => 'Delete User',
                'sort' => 10,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'activate-user',
                'display_name' => 'Activate User',
                'sort' => 11,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'deactivate-user',
                'display_name' => 'Deactivate User',
                'sort' => 12,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'login-as-user',
                'display_name' => 'Login As User',
                'sort' => 13,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'clear-user-session',
                'display_name' => 'Clear User Session',
                'sort' => 14,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'view-role-management',
                'display_name' => 'View Role Management',
                'sort' => 15,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'create-role',
                'display_name' => 'Create Role',
                'sort' => 16,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'edit-role',
                'display_name' => 'Edit Role',
                'sort' => 17,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'delete-role',
                'display_name' => 'Delete Role',
                'sort' => 18,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'view-permission-management',
                'display_name' => 'View Permission Management',
                'sort' => 19,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'create-permission',
                'display_name' => 'Create Permission',
                'sort' => 20,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'edit-permission',
                'display_name' => 'Edit Permission',
                'sort' => 21,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'delete-permission',
                'display_name' => 'Delete Permission',
                'sort' => 22,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'view-page',
                'display_name' => 'View Page',
                'sort' => 23,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'create-page',
                'display_name' => 'Create Page',
                'sort' => 24,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'edit-page',
                'display_name' => 'Edit Page',
                'sort' => 25,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'delete-page',
                'display_name' => 'Delete Page',
                'sort' => 26,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'name' => 'view-email-template',
                'display_name' => 'View Email Templates',
                'sort' => 27,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'name' => 'create-email-template',
                'display_name' => 'Create Email Templates',
                'sort' => 28,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'name' => 'edit-email-template',
                'display_name' => 'Edit Email Templates',
                'sort' => 29,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'name' => 'delete-email-template',
                'display_name' => 'Delete Email Templates',
                'sort' => 30,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'name' => 'edit-settings',
                'display_name' => 'Edit Settings',
                'sort' => 31,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'name' => 'view-blog-category',
                'display_name' => 'View Blog Categories Management',
                'sort' => 32,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 34,
                'name' => 'create-blog-category',
                'display_name' => 'Create Blog Category',
                'sort' => 33,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 35,
                'name' => 'edit-blog-category',
                'display_name' => 'Edit Blog Category',
                'sort' => 34,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 36,
                'name' => 'delete-blog-category',
                'display_name' => 'Delete Blog Category',
                'sort' => 35,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 37,
                'name' => 'view-blog-tag',
                'display_name' => 'View Blog Tags Management',
                'sort' => 36,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 38,
                'name' => 'create-blog-tag',
                'display_name' => 'Create Blog Tag',
                'sort' => 37,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 39,
                'name' => 'edit-blog-tag',
                'display_name' => 'Edit Blog Tag',
                'sort' => 38,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 40,
                'name' => 'delete-blog-tag',
                'display_name' => 'Delete Blog Tag',
                'sort' => 39,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 41,
                'name' => 'view-blog',
                'display_name' => 'View Blogs Management',
                'sort' => 40,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 42,
                'name' => 'create-blog',
                'display_name' => 'Create Blog',
                'sort' => 41,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 43,
                'name' => 'edit-blog',
                'display_name' => 'Edit Blog',
                'sort' => 42,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 44,
                'name' => 'delete-blog',
                'display_name' => 'Delete Blog',
                'sort' => 43,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 45,
                'name' => 'view-faq',
                'display_name' => 'View FAQ Management',
                'sort' => 44,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 46,
                'name' => 'create-faq',
                'display_name' => 'Create FAQ',
                'sort' => 45,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 47,
                'name' => 'edit-faq',
                'display_name' => 'Edit FAQ',
                'sort' => 46,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 48,
                'name' => 'delete-faq',
                'display_name' => 'Delete FAQ',
                'sort' => 47,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 09:39:46',
                'updated_at' => '2018-07-06 09:39:46',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 49,
                'name' => 'manage-product',
                'display_name' => 'Manage Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 50,
                'name' => 'create-product',
                'display_name' => 'Create Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 51,
                'name' => 'store-product',
                'display_name' => 'Store Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 52,
                'name' => 'edit-product',
                'display_name' => 'Edit Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 53,
                'name' => 'update-product',
                'display_name' => 'Update Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 54,
                'name' => 'delete-product',
                'display_name' => 'Delete Product Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:38:55',
                'updated_at' => '2018-07-06 11:38:55',
                'deleted_at' => NULL,
            ),
            54 => 
            array (
                'id' => 55,
                'name' => 'manage-category',
                'display_name' => 'Manage Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:51',
                'updated_at' => '2018-07-06 11:50:51',
                'deleted_at' => NULL,
            ),
            55 => 
            array (
                'id' => 56,
                'name' => 'create-category',
                'display_name' => 'Create Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:51',
                'updated_at' => '2018-07-06 11:50:51',
                'deleted_at' => NULL,
            ),
            56 => 
            array (
                'id' => 57,
                'name' => 'store-category',
                'display_name' => 'Store Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:52',
                'updated_at' => '2018-07-06 11:50:52',
                'deleted_at' => NULL,
            ),
            57 => 
            array (
                'id' => 58,
                'name' => 'edit-category',
                'display_name' => 'Edit Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:52',
                'updated_at' => '2018-07-06 11:50:52',
                'deleted_at' => NULL,
            ),
            58 => 
            array (
                'id' => 59,
                'name' => 'update-category',
                'display_name' => 'Update Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:52',
                'updated_at' => '2018-07-06 11:50:52',
                'deleted_at' => NULL,
            ),
            59 => 
            array (
                'id' => 60,
                'name' => 'delete-category',
                'display_name' => 'Delete Category Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 11:50:52',
                'updated_at' => '2018-07-06 11:50:52',
                'deleted_at' => NULL,
            ),
            60 => 
            array (
                'id' => 61,
                'name' => 'manage-service',
                'display_name' => 'Manage Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            61 => 
            array (
                'id' => 62,
                'name' => 'create-service',
                'display_name' => 'Create Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            62 => 
            array (
                'id' => 63,
                'name' => 'store-service',
                'display_name' => 'Store Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            63 => 
            array (
                'id' => 64,
                'name' => 'edit-service',
                'display_name' => 'Edit Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            64 => 
            array (
                'id' => 65,
                'name' => 'update-service',
                'display_name' => 'Update Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            65 => 
            array (
                'id' => 66,
                'name' => 'delete-service',
                'display_name' => 'Delete Service Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-06 14:28:01',
                'updated_at' => '2018-07-06 14:28:01',
                'deleted_at' => NULL,
            ),
            66 => 
            array (
                'id' => 67,
                'name' => 'manage-device',
                'display_name' => 'Manage Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            67 => 
            array (
                'id' => 68,
                'name' => 'create-device',
                'display_name' => 'Create Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            68 => 
            array (
                'id' => 69,
                'name' => 'store-device',
                'display_name' => 'Store Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            69 => 
            array (
                'id' => 70,
                'name' => 'edit-device',
                'display_name' => 'Edit Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            70 => 
            array (
                'id' => 71,
                'name' => 'update-device',
                'display_name' => 'Update Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            71 => 
            array (
                'id' => 72,
                'name' => 'delete-device',
                'display_name' => 'Delete Device Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-10 06:55:47',
                'updated_at' => '2018-07-10 06:55:47',
                'deleted_at' => NULL,
            ),
            72 => 
            array (
                'id' => 73,
                'name' => 'manage-coupon',
                'display_name' => 'Manage Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            73 => 
            array (
                'id' => 74,
                'name' => 'create-coupon',
                'display_name' => 'Create Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            74 => 
            array (
                'id' => 75,
                'name' => 'store-coupon',
                'display_name' => 'Store Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            75 => 
            array (
                'id' => 76,
                'name' => 'edit-coupon',
                'display_name' => 'Edit Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            76 => 
            array (
                'id' => 77,
                'name' => 'update-coupon',
                'display_name' => 'Update Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            77 => 
            array (
                'id' => 78,
                'name' => 'delete-coupon',
                'display_name' => 'Delete Coupon Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-12 06:03:06',
                'updated_at' => '2018-07-12 06:03:06',
                'deleted_at' => NULL,
            ),
            78 => 
            array (
                'id' => 79,
                'name' => 'manage-contact',
                'display_name' => 'Manage Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            79 => 
            array (
                'id' => 80,
                'name' => 'create-contact',
                'display_name' => 'Create Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            80 => 
            array (
                'id' => 81,
                'name' => 'store-contact',
                'display_name' => 'Store Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            81 => 
            array (
                'id' => 82,
                'name' => 'edit-contact',
                'display_name' => 'Edit Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            82 => 
            array (
                'id' => 83,
                'name' => 'update-contact',
                'display_name' => 'Update Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            83 => 
            array (
                'id' => 84,
                'name' => 'delete-contact',
                'display_name' => 'Delete Contact Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:21:35',
                'updated_at' => '2018-07-20 13:21:35',
                'deleted_at' => NULL,
            ),
            84 => 
            array (
                'id' => 85,
                'name' => 'manage-ordercomplain',
                'display_name' => 'Manage Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            85 => 
            array (
                'id' => 86,
                'name' => 'create-ordercomplain',
                'display_name' => 'Create Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            86 => 
            array (
                'id' => 87,
                'name' => 'store-ordercomplain',
                'display_name' => 'Store Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            87 => 
            array (
                'id' => 88,
                'name' => 'edit-ordercomplain',
                'display_name' => 'Edit Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            88 => 
            array (
                'id' => 89,
                'name' => 'update-ordercomplain',
                'display_name' => 'Update Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            89 => 
            array (
                'id' => 90,
                'name' => 'delete-ordercomplain',
                'display_name' => 'Delete Ordercomplain Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-07-20 13:54:19',
                'updated_at' => '2018-07-20 13:54:19',
                'deleted_at' => NULL,
            ),
            90 => 
            array (
                'id' => 91,
                'name' => 'manage-translation',
                'display_name' => 'Manage Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:26',
                'updated_at' => '2018-08-08 14:03:26',
                'deleted_at' => NULL,
            ),
            91 => 
            array (
                'id' => 92,
                'name' => 'create-translation',
                'display_name' => 'Create Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:26',
                'updated_at' => '2018-08-08 14:03:26',
                'deleted_at' => NULL,
            ),
            92 => 
            array (
                'id' => 93,
                'name' => 'store-translation',
                'display_name' => 'Store Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:26',
                'updated_at' => '2018-08-08 14:03:26',
                'deleted_at' => NULL,
            ),
            93 => 
            array (
                'id' => 94,
                'name' => 'edit-translation',
                'display_name' => 'Edit Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:26',
                'updated_at' => '2018-08-08 14:03:26',
                'deleted_at' => NULL,
            ),
            94 => 
            array (
                'id' => 95,
                'name' => 'update-translation',
                'display_name' => 'Update Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:27',
                'updated_at' => '2018-08-08 14:03:27',
                'deleted_at' => NULL,
            ),
            95 => 
            array (
                'id' => 96,
                'name' => 'delete-translation',
                'display_name' => 'Delete Translation Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 14:03:27',
                'updated_at' => '2018-08-08 14:03:27',
                'deleted_at' => NULL,
            ),
            96 => 
            array (
                'id' => 97,
                'name' => 'manage-notification',
                'display_name' => 'Manage Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            97 => 
            array (
                'id' => 98,
                'name' => 'create-notification',
                'display_name' => 'Create Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            98 => 
            array (
                'id' => 99,
                'name' => 'store-notification',
                'display_name' => 'Store Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            99 => 
            array (
                'id' => 100,
                'name' => 'edit-notification',
                'display_name' => 'Edit Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            100 => 
            array (
                'id' => 101,
                'name' => 'update-notification',
                'display_name' => 'Update Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            101 => 
            array (
                'id' => 102,
                'name' => 'delete-notification',
                'display_name' => 'Delete Notification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:31:35',
                'updated_at' => '2018-08-08 15:31:35',
                'deleted_at' => NULL,
            ),
            102 => 
            array (
                'id' => 103,
                'name' => 'manage-pushnotification',
                'display_name' => 'Manage Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
            103 => 
            array (
                'id' => 104,
                'name' => 'create-pushnotification',
                'display_name' => 'Create Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
            104 => 
            array (
                'id' => 105,
                'name' => 'store-pushnotification',
                'display_name' => 'Store Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
            105 => 
            array (
                'id' => 106,
                'name' => 'edit-pushnotification',
                'display_name' => 'Edit Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
            106 => 
            array (
                'id' => 107,
                'name' => 'update-pushnotification',
                'display_name' => 'Update Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
            107 => 
            array (
                'id' => 108,
                'name' => 'delete-pushnotification',
                'display_name' => 'Delete Pushnotification Permission',
                'sort' => 0,
                'status' => 1,
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2018-08-08 15:38:56',
                'updated_at' => '2018-08-08 15:38:56',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}