<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Blanket',
                'name_ar' => 'بطانية',
                'slug' => 'blanket',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-07-26 06:11:17',
                'updated_at' => '2018-07-26 06:11:17',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'Shirt',
                'name_ar' => 'قميص',
                'slug' => 'shirt',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-07-26 06:56:36',
                'updated_at' => '2018-07-26 06:56:36',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 8,
                'name' => 'Custom Garment',
                'name_ar' => 'Custom Garment',
                'slug' => 'custom-garment',
                'status' => 1,
                'is_custom' => 1,
                'picture' => NULL,
                'created_at' => '2018-07-30 16:08:48',
                'updated_at' => '2018-07-30 16:08:48',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 9,
                'name' => 'Summer Thobe',
                'name_ar' => 'ثوب صيفي',
                'slug' => 'summer-thobe',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:28:09',
                'updated_at' => '2018-08-04 10:28:09',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 10,
                'name' => 'Winter Thobe',
                'name_ar' => 'ثوب شتوي',
                'slug' => 'winter-thobe',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:28:43',
                'updated_at' => '2018-08-04 10:28:43',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 11,
                'name' => 'Ghutra/Shimagh',
                'name_ar' => 'غتره /شماغ',
                'slug' => 'ghutrashimagh',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:29:27',
                'updated_at' => '2018-08-04 10:29:27',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 12,
                'name' => 'Hat',
                'name_ar' => 'طاقية',
                'slug' => 'hat',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:30:01',
                'updated_at' => '2018-08-04 10:30:01',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 13,
                'name' => 'Undershirt',
                'name_ar' => 'فانيلة داخلية',
                'slug' => 'undershirt',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:30:17',
                'updated_at' => '2018-08-04 10:30:17',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 14,
                'name' => 'Short Underwear',
                'name_ar' => 'سروال سنة قصير',
                'slug' => 'short-underwear',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:30:42',
                'updated_at' => '2018-08-04 10:30:42',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 15,
                'name' => 'Long Underwear',
                'name_ar' => 'سروال سنة طويل',
                'slug' => 'long-underwear',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:30:56',
                'updated_at' => '2018-08-04 10:30:56',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 16,
            'name' => 'Socks (2 pc.)',
                'name_ar' => 'شراب',
                'slug' => 'socks-2-pc',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:31:32',
                'updated_at' => '2018-08-04 10:31:32',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 17,
            'name' => 'Track Suit (Bottoms)',
                'name_ar' => 'بنطلون بدلة رياضية',
                'slug' => 'track-suit-bottoms',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:32:00',
                'updated_at' => '2018-08-04 10:32:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 18,
            'name' => 'Track Suit (Jacket)',
                'name_ar' => 'قميص بدله رياضية',
                'slug' => 'track-suit-jacket',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:32:23',
                'updated_at' => '2018-08-04 10:32:23',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 19,
            'name' => 'Pajamas (2pc)',
                'name_ar' => 'بيجامة قطعتين',
                'slug' => 'pajamas-2pc',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:32:38',
                'updated_at' => '2018-08-04 10:32:38',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 20,
                'name' => 'Military Berets',
                'name_ar' => 'بريه عسكرية',
                'slug' => 'military-berets',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:32:55',
                'updated_at' => '2018-08-04 10:32:55',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 21,
                'name' => 'Overalls',
                'name_ar' => 'اوفر هول',
                'slug' => 'overalls',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:33:12',
                'updated_at' => '2018-08-04 10:33:12',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 22,
                'name' => 'Police Unifrom',
                'name_ar' => 'بدلة عسكرية',
                'slug' => 'police-unifrom',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:33:36',
                'updated_at' => '2018-08-04 10:33:36',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 23,
                'name' => 'Suit Jacket',
                'name_ar' => 'جاكيت بدلة',
                'slug' => 'suit-jacket',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:33:57',
                'updated_at' => '2018-08-04 10:33:57',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 24,
                'name' => 'Suit Pants',
                'name_ar' => 'بنطلون بدلة رسمية',
                'slug' => 'suit-pants',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:34:17',
                'updated_at' => '2018-08-04 10:34:17',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 25,
                'name' => 'Silk Dress Shirt',
                'name_ar' => 'قميص حرير',
                'slug' => 'silk-dress-shirt',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:34:34',
                'updated_at' => '2018-08-04 10:34:34',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 26,
                'name' => 'Bisht',
                'name_ar' => 'بشت',
                'slug' => 'bisht',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:34:49',
                'updated_at' => '2018-08-04 10:34:49',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 27,
                'name' => 'Coat',
                'name_ar' => 'بالطو',
                'slug' => 'coat',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:35:05',
                'updated_at' => '2018-08-04 10:35:05',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 28,
                'name' => 'Tie',
                'name_ar' => 'كرفته',
                'slug' => 'tie',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:35:21',
                'updated_at' => '2018-08-04 10:35:21',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 29,
                'name' => 'Dress Shirt',
                'name_ar' => 'قميص عادي',
                'slug' => 'dress-shirt',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:35:37',
                'updated_at' => '2018-08-04 10:35:37',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 30,
                'name' => 'Silk Shirt',
                'name_ar' => 'بلوزة حرير',
                'slug' => 'silk-shirt',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:35:53',
                'updated_at' => '2018-08-04 10:35:53',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 31,
                'name' => 'Women Jeans',
                'name_ar' => 'بنطلون نسائي',
                'slug' => 'women-jeans',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:36:26',
                'updated_at' => '2018-08-04 10:36:26',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 32,
                'name' => 'Abaya',
                'name_ar' => 'عباية',
                'slug' => 'abaya',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:36:43',
                'updated_at' => '2018-08-04 10:36:43',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 33,
                'name' => 'Small Towel',
                'name_ar' => 'فوطة صغيرة',
                'slug' => 'small-towel',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:36:57',
                'updated_at' => '2018-08-04 10:36:57',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 34,
                'name' => 'Large Towel',
                'name_ar' => 'منشفة كبيرة',
                'slug' => 'large-towel',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:37:21',
                'updated_at' => '2018-08-04 10:37:21',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 35,
                'name' => 'Blanket',
                'name_ar' => 'بطانية',
                'slug' => 'blanket-1',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:37:41',
                'updated_at' => '2018-08-04 10:37:41',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 36,
                'name' => 'Comforter',
                'name_ar' => 'مفرش',
                'slug' => 'comforter',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:38:02',
                'updated_at' => '2018-08-04 10:38:02',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 37,
            'name' => 'Dress (Premium Care)',
                'name_ar' => 'فستان',
                'slug' => 'dress-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:42:20',
                'updated_at' => '2018-08-04 10:42:20',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 38,
            'name' => 'Wedding Dress (Premium Care)',
                'name_ar' => 'فستان عروس',
                'slug' => 'wedding-dress-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:42:57',
                'updated_at' => '2018-08-04 11:14:25',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 39,
            'name' => 'Silk Dress (Premium Care)',
                'name_ar' => 'فستان حرير',
                'slug' => 'silk-dress-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:43:18',
                'updated_at' => '2018-08-04 11:14:42',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 40,
            'name' => '2 Piece Dress (Premium Care)',
                'name_ar' => 'فستان قطعاتين',
                'slug' => '2-piece-dress-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:43:39',
                'updated_at' => '2018-08-04 11:15:03',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 41,
            'name' => 'Skirt (Premium Care)',
                'name_ar' => 'تنورة',
                'slug' => 'skirt-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:43:52',
                'updated_at' => '2018-08-04 11:15:44',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 42,
            'name' => 'Pleated Skirt (Premium Care)',
                'name_ar' => 'تنورة تكسير',
                'slug' => 'pleated-skirt-premium-care',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:44:04',
                'updated_at' => '2018-08-04 11:16:06',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 43,
            'name' => 'Normal Carpets (1pc=1meter)',
                'name_ar' => 'سجاد عادي',
                'slug' => 'normal-carpets-1pc1meter',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:44:23',
                'updated_at' => '2018-08-04 11:19:05',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 44,
                'name' => 'National Carpets',
                'name_ar' => 'سجاد وطني',
                'slug' => 'national-carpets',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:44:37',
                'updated_at' => '2018-08-04 10:44:37',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 45,
            'name' => 'Hairy Carpets (Carpets with long hairy texture)',
                'name_ar' => 'سجاد شعر',
                'slug' => 'hairy-carpets-carpets-with-long-hairy-texture',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:44:51',
                'updated_at' => '2018-08-04 10:44:51',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 46,
                'name' => 'Persian Rugs',
                'name_ar' => 'سجاد إيراني',
                'slug' => 'persian-rugs',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:45:15',
                'updated_at' => '2018-08-04 10:45:15',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 47,
            'name' => 'Curtains (1pc=1meter)',
            'name_ar' => 'ستائر (القطعة) بالمتر',
                'slug' => 'curtains-1pc1meter',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:45:39',
                'updated_at' => '2018-08-04 10:45:39',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 48,
                'name' => 'Fitted Sheets',
                'name_ar' => 'شرشف مزدوج',
                'slug' => 'fitted-sheets',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:46:26',
                'updated_at' => '2018-08-04 10:46:26',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 49,
                'name' => 'Pillow Case',
                'name_ar' => 'كيس مخدة',
                'slug' => 'pillow-case',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:46:38',
                'updated_at' => '2018-08-04 10:46:38',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 50,
                'name' => 'Single Sheet',
                'name_ar' => 'شرشف مفرد',
                'slug' => 'single-sheet',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:46:50',
                'updated_at' => '2018-08-04 10:46:50',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 51,
                'name' => 'Bathrobe',
                'name_ar' => 'روب حمام',
                'slug' => 'bathrobe',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-04 10:47:05',
                'updated_at' => '2018-08-04 10:47:05',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 52,
                'name' => 'Ehram',
                'name_ar' => 'أحرام',
                'slug' => 'ehram',
                'status' => 1,
                'is_custom' => 0,
                'picture' => NULL,
                'created_at' => '2018-08-09 17:06:37',
                'updated_at' => '2018-08-09 17:06:37',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}